// Package declaration
package gr.aueb.cf.schoolapp.model.static_data;

// Import statements for related classes and libraries
import gr.aueb.cf.schoolapp.model.Teacher;
import jakarta.persistence.*;
import lombok.*;

import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

// Marks this class as a JPA entity mapped to a database table
@Entity
// Lombok: generates a no-argument constructor
@NoArgsConstructor
// Lombok: generates a constructor with all arguments
@AllArgsConstructor
// Lombok: generates getter methods for all fields
@Getter
// Lombok: generates setter methods for all fields
@Setter
// Specifies the table name in the database
@Table(name = "regions")
public class Region {

    // Primary key, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Name of the region
    private String name;

    // One region can have many teachers (lazy loading)
    // Lombok: getter is private for this field
    @Getter(AccessLevel.PRIVATE)
    @OneToMany(mappedBy = "region", fetch = FetchType.LAZY)
    private Set<Teacher> teachers = new HashSet<>();

    // Returns an unmodifiable view of the teachers set
    public Set<Teacher> getAllTeachers() {
        return Collections.unmodifiableSet(teachers);
    }

    // Adds a teacher to the region and sets the region in the teacher
    public void addTeacher(Teacher teacher) {
        if (teachers == null) teachers = new HashSet<>();
        teachers.add(teacher);
        teacher.setRegion(this);
    }
}