package gr.aueb.cf.schoolapp.model;

// Importing the Region entity from static_data package
import gr.aueb.cf.schoolapp.model.static_data.Region;
// JPA and Lombok imports
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.UUID;

// Marks this class as a JPA entity mapped to a database table
@Entity
// Lombok: generates a no-argument constructor
@NoArgsConstructor
// Lombok: generates a constructor with all arguments
@AllArgsConstructor
// Lombok: generates getter methods for all fields
@Getter
// Lombok: generates setter methods for all fields
@Setter
// Specifies the table name in the database
@Table(name = "teachers")
public class Teacher extends AbstractEntity {

    // Primary key, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Unique string identifier (UUID) for the teacher
    @Column(unique = true)
    private String uuid;

    // Unique VAT (AFM) number for the teacher
    @Column(unique = true)
    private String vat;

    // Teacher's first name
    private String firstName;
    // Teacher's last name
    private String lastName;

    // Many teachers can belong to one region (lazy loading)
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "region_id")
    private Region region;

    // Before persisting, generate a UUID if not already set
    @PrePersist
    public void initializeUUID() {
        if (uuid == null) uuid = UUID.randomUUID().toString();
    }
}